### ISSUE TITLE
xSQLServerSetup does not work repliably

### ISSUE THREAD

**Issue by kiransaa** [PowerShell/xSQLServer#152]
I have been trying to get this to work but i get this error every time:

```

VERBOSE: [myServer]:                            [[xSQLServerSetup]installSQL] Test-TargetResource returned false after calling set. | ErrorType: MSFT_xSQLServerSetup.TestFailedAfterSet
VERBOSE: [myServer]: LCM:  [ End    Set      ]  [[xSQLServerSetup]installSQL]  in 63.3120 seconds.
PowerShell DSC resource MSFT_xSQLServerSetup  failed to execute Set-TargetResource functionality with error message: Test-TargetResource returned false after calling set. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

i check program files and dont see an "sql server" folder there. I check the %temp% folder nothing there as well.

The DSC logs are not helpful either:

```
Job {1983FE4E-8BC6-11E6-80C4-000D3A20899A} : 
MIResult: 1
Error Message: PowerShell DSC resource MSFT_xSQLServerSetup  failed to execute Set-TargetResource functionality with error message: Test-TargetResource returned false after calling set. 
Message ID: ProviderOperationExecutionFailure
Error Category: 7
Error Code: 1
Error Type: MI
```

```
Job {1983FE4E-8BC6-11E6-80C4-000D3A20899A} : 
Message Test-TargetResource returned false after calling set. 
HResult -2146233087 
StackTrack    at System.Management.Automation.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

so not sure how to troubleshoot this thing.

Also it seems the path to the setup files has been hardcoded so we have to have the setup files in a folder called "sources".For people like me who use ISO's this forces us to re-package the iso with the sources folder.

**Comment by luigilink** [comment]
I had this issue, and I ran the setup manually, I saw a pending restart.
After a reboot, install was a success.

**Comment by kiransaa** [comment]
thanks for the reply @luigilink ....i got it working by re-downloading the ISO(must have been a bad download)...i am using Azure and ARM templates with azure automation dsc so i can roll out a lot of vm's in quick time...so far every time i have deployed a vm i have got the error "test failed after set" and although DSC consistency check reports a failure for all vm's sql does in fact get installed...but weirdly on some it installs 12 new apps and on others 15 apps...the process is exactly the same but get different results...I am not sure if this is happening because I am using an ISO but that shouldn't matter should it?It is hard to believe that this is working for everyone else.

**Comment by johlju** [comment]
@kiransaa It shouldn't make any difference if you are using an ISO or media on the hard drive. As long as the installation account (`SourceCredential` or `PsDscRunAsCredential`) has access to the media. It apparently have since you seem to get it to install.

Can you see in any logs of what is going on? SQL setup log or any log from the automation? I want to figure out if there is a bug here, and if so, where it is. :)

**Comment by simonh-tm** [comment]
Is this issue resolved by #126 at all? I've seen this exact same issue immediately resolved if I apply that change.

**Comment by kiransaa** [comment]
@johlju ..there is definitely a bug because like a mentioned, irrespective of what i do i get the error "set failed after test" but the install goes through..i spent quite a bit of time trying to troubleshoot but gave up due to the C# code and the nested module structure on....the VM's have since been deleted because they were on azure and i was using them for testing..will post the sql log here when i create a new vm one .... also the "full-text" service does not use the service account even though it is provided as a parameter.

**Comment by kiransaa** [comment]
to summarize 3 issues encountered so far:

1. "set failed after test"
2. "full-text" service does not use the service account even though it is provided as a parameter.
3. The install path(path to setup.exe) must not be hard-coded in the DSC resource module.

**Comment by kiransaa** [comment]
seems this has been set to default but can specify a value in the resource?

<Setting Id="FTSVCACCOUNT" Value="NT Service\MSSQLFDLauncher$INST1" Source="Default" IsApplicable="true" IsChangeableByUser="false" />
