### ISSUE TITLE
xSQLServerSetup: Parameter AGTSVCSTARTUPTYPE should not be passed with clustered installs

### ISSUE THREAD

**Issue by yardbirdsax** [PowerShell/xSQLServer#344]
**Details of the scenario you try and problem that is occurring:**
When using the resource for clustered installations the AGTSVCSTARTUPTYPE command line parameter should not be passed to the setup process.

Below is the text from the setup log:

`
Exception type: Microsoft.SqlServer.Chainer.Infrastructure.InputSettingValidationException
    Message: 
        The setting 'AGTSVCSTARTUPTYPE' is not allowed when the value of setting 'ACTION' is 'InstallFailoverCluster'.
    HResult : 0x84b40005
        FacilityCode : 1204 (4b4)
        ErrorCode : 5 (0005)
    Data: 
      SQL.Setup.FailureCategory = InputSettingValidationFailure
      DisableWatson = true
    Stack: 
        at Microsoft.SqlServer.Chainer.Infrastructure.InputSettingService.LogAllValidationErrorsAndThrowFirstOne(ValidationState vs)
        at Microsoft.SqlServer.Configuration.BootstrapExtension.ValidateSettingsAgainstScenarioAction.ExecuteAction(String actionId)
        at Microsoft.SqlServer.Chainer.Infrastructure.Action.Execute(String actionId, TextWriter errorStream)
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.<>c__DisplayClasse.<ExecuteActionWithRetryHelper>b__b()
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.ExecuteActionHelper(ActionWorker workerDelegate)
`

**The DSC configuration that is using the resource (as detailed as possible):**
Any configuration that specifies an action of "InstallFailoverCluster", "AddNode", "PrepareFailoverCluster", or "CompleteFailoverCluster".

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
SQL Server 2016, Windows 2016

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by yardbirdsax** [comment]
I've got this one fixed, just need to get work done for the other issues I've submitted.
