### ISSUE TITLE
xSQLServerSetup: Should be able to uninstall a cluster node.

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#434]
**Details of the scenario you try and problem that is occurring:**
The resource should support uninstall a cluster node.

```
.\setup.exe /q /ACTION=RemoveNode /INSTANCENAME="SQL2014" /CONFIRMIPDEPENDENCYCHANGE=
```

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
When uninstalling manually with the above command, a reboot was required before I could install a new instance.

```
Exception type: Microsoft.SqlServer.Configuration.RulesEngineExtension.RulesEngineRuleFailureException
    Message: 
        A computer restart is required. You must restart this computer before installing SQL Server.
    HResult : 0x84be0bc2
        FacilityCode : 1214 (4be)
        ErrorCode : 3010 (0bc2)
    Data: 
      SQL.Setup.FailureCategory = RuleViolationFailure
      DisableWatson = true
    Stack: 
        at Microsoft.SqlServer.Configuration.RulesEngineExtension.RunRulesAction.ExecuteAction(String actionId)
        at Microsoft.SqlServer.Chainer.Infrastructure.Action.Execute(String actionId, TextWriter errorStream)
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.<>c__DisplayClasse.<ExecuteActionWithRetryHelper>b__b()
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.ExecuteActionHelper(ActionWorker workerDelegate)
```

**Comment by johlju** [comment]
More information about RemoveNode: 
https://msdn.microsoft.com/en-us/library/ms144259.aspx#Anchor_8
https://msdn.microsoft.com/en-us/library/ms144259.aspx#Feature
